steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/kasa-backend-prod:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/kasa-backend-prod:latest',
      '--build-arg', 'NODE_ENV=production',
      '-f', 'Backend/Kasa_Backend/backend/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/kasa-backend-test:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/kasa-backend-test:latest',
      '--build-arg', 'NODE_ENV=test',
      '-f', 'Backend/Kasa_Backend/backend/Dockerfile',
      '.'
    ]
  # Push production images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kasa-backend-prod:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kasa-backend-prod:latest']

  # Push test images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kasa-backend-test:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kasa-backend-test:latest']

images:
  - 'gcr.io/$PROJECT_ID/kasa-backend-prod:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/kasa-backend-prod:latest'
  - 'gcr.io/$PROJECT_ID/kasa-backend-test:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/kasa-backend-test:latest'
